<a href="https://colab.research.google.com/github/AbdulAhad696/pytorch_YTCourse/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")
import torch
import pandas
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

Hello
2.0.1+cu118


In [ ]:
X = torch.rand(12288,208)
X.shape

torch.Size([12288, 208])

In [ ]:
W = torch.rand(12288,4) * torch.math.sqrt(2/3)
W.shape

torch.Size([12288, 4])

In [ ]:
b = torch.zeros(4,1)
b

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [ ]:
Z = torch.rand_like(W)
Z.shape

torch.Size([12288, 4])

In [ ]:
test = torch.rand(10)
test.shape
test2 = torch.rand(10)
test.shape
Z = torch.dot(test,test2)
Z

tensor(2.5382)

In [ ]:
dTensor = torch.rand(208,64,64,3)
dTensor.shape

torch.Size([208, 64, 64, 3])

In [ ]:
dTensor.ndim

4

In [ ]:
torch.rand(3,1)

tensor([[0.8400],
        [0.0354],
        [0.3137]])

In [ ]:
Z = torch.matmul(W.T,X)

In [ ]:
Z.shape

torch.Size([4, 208])

In [ ]:
Z.dtype

torch.float32

In [ ]:
Z.ndim

2

In [ ]:
Z = Z.type(torch.float16)

In [ ]:
Z.dtype

torch.float16

In [ ]:
A = W.T @ X
Z-A

tensor([[ 8.1348e-01,  2.1729e-02,  5.7007e-01, -1.2085e-01, -3.6377e-01,
         -7.1436e-01, -6.0645e-01, -4.5850e-01, -3.9844e-01, -8.0933e-01,
         -8.7256e-01,  1.4526e-01,  9.4214e-01,  8.5864e-01,  9.5044e-01,
         -3.3374e-01,  3.3472e-01, -2.6562e-01,  2.1680e-01, -7.3096e-01,
         -2.8589e-01,  3.5962e-01, -4.8022e-01, -3.2471e-01,  8.4741e-01,
          8.7158e-01, -1.4624e-01, -1.0010e-01, -3.5059e-01,  1.6821e-01,
          4.0869e-01, -3.1689e-01,  4.4971e-01, -8.1909e-01,  7.9053e-01,
          8.5889e-01, -5.6763e-01, -7.6929e-01,  3.4985e-01,  1.4331e-01,
         -3.3130e-01, -3.0029e-02, -8.1470e-01,  6.7871e-02, -9.4482e-02,
         -7.2900e-01,  4.2456e-01,  6.7285e-01,  1.5796e-01, -7.1899e-01,
         -5.2856e-01,  3.4717e-01,  8.0933e-01, -9.5215e-03, -7.2559e-01,
         -6.0059e-02, -8.7500e-01, -2.6733e-01, -2.9419e-01,  2.2144e-01,
         -1.1182e-01, -3.3447e-02,  9.8022e-01,  6.7749e-01, -9.6265e-01,
         -1.4648e-01,  6.3965e-01, -2.

In [ ]:
x = torch.arange(-69,10)

In [ ]:
%%time
torch.mean(x,dtype=torch.float16)

CPU times: user 1.11 ms, sys: 0 ns, total: 1.11 ms
Wall time: 1.12 ms


tensor(-30., dtype=torch.float16)

In [ ]:
%%time
torch.mean(x.type(torch.float16))

CPU times: user 174 µs, sys: 10 µs, total: 184 µs
Wall time: 189 µs


tensor(-30., dtype=torch.float16)

In [ ]:
%%time
x.type(torch.float16).mean()

CPU times: user 176 µs, sys: 11 µs, total: 187 µs
Wall time: 195 µs


tensor(-30., dtype=torch.float16)

In [ ]:
%%time
torch.sum(x)

CPU times: user 102 µs, sys: 0 ns, total: 102 µs
Wall time: 106 µs


tensor(-2370)

In [ ]:
%%time
x.sum()

CPU times: user 96 µs, sys: 6 µs, total: 102 µs
Wall time: 108 µs


tensor(-2370)

In [ ]:
%%time
x.min()

CPU times: user 66 µs, sys: 4 µs, total: 70 µs
Wall time: 74.4 µs


tensor(-69)

In [ ]:
%%time
torch.min(x)

CPU times: user 76 µs, sys: 0 ns, total: 76 µs
Wall time: 80.1 µs


tensor(-69)

In [ ]:
%%time
torch.max(x)

CPU times: user 69 µs, sys: 2 µs, total: 71 µs
Wall time: 74.4 µs


tensor(9)

In [ ]:
%%time
x.max()

CPU times: user 69 µs, sys: 4 µs, total: 73 µs
Wall time: 76.8 µs


tensor(9)

In [ ]:
x.argmax()

tensor(78)